### PR TITLE
fix: add logic to shuffle

### LINKED ISSUE #27: When getting the color for a new reminder, shuffle through the array based on previous reminder
Right now, a new reminder will have a _random_ color assigned to it. This means we might create 2 reminders with the same color back to back. Instead, let's only get a random color if they have no existing reminders otherwise we cycle through the colors one at a time.

Eg. if the last reminder was `blue`, the next one will be `green` (see [`BRAND_COLORS` array](https://github.com/12products/poke-frontend/blob/main/constants/Colors.ts#L1-L9))

### PR DESCRIPTION
**Pull request by alicelovescake**
This PR:

- [x] Resolves #27

### CODE REVIEW

File: lib/utils.ts [hunk 1]
```diff
@@ -15,8 +16,13 @@ export const numToDays = [
...
 ]
 
-export const getRandomBrandColor = () =>
-  BRAND_COLORS[Math.floor(Math.random() * BRAND_COLORS.length)]
+export const getRandomBrandColor = () => {
+  const reminders = useReminderStore((state) => state.reminders)
+  const idx = reminders.length
+    ? reminders.length % BRAND_COLORS.length
+    : Math.floor(Math.random() * BRAND_COLORS.length)
+  BRAND_COLORS[idx]
```
Comment (amorriscode) [inline lib/utils.ts]: Let's leave `getRandomBrandColor` as is. Instead, inside the create reminder screen we'll just assign the color to `BRAND_COLORS[reminders.length % BRAND_COLORS.length]`.
